// AUTO-GENERATED by art/export_json.py — do not edit by hand.
window.GAME_DATA = {
"palette": {
".": null,
"K": "#251e33",
"W": "#f4f4ee",
"S": "#ffce9e",
"s": "#d88c58",
"R": "#ff5d5d",
"r": "#be3238",
"B": "#5db4ff",
"b": "#2f64af",
"H": "#b06434",
"h": "#683a1e",
"G": "#6bd66b",
"g": "#2f8c50",
"Y": "#ffd54a",
"L": "#c2c7d0",
"D": "#5a6375"
},
"roster": [
{
"name": "PIXEL",
"accent": "#ff5d5d",
"rows": [
".........KKKKKK.........",
".......KhhhhhhhhK.......",
"......KhhhHHHhhhhK......",
".....KhhhhHHhhhhhhK.....",
".....KhhSSSSSSSShhK.....",
".....KhhShSSSShShhK.....",
".....KhhSKKSSKKShhK.....",
".....KhhSWKSSWKShhK.....",
".....KhhSsSSSSsShhK.....",
".....KhhSSKrrKSShhK.....",
"......KhSSssssSShK......",
"........KSSSSSSK........",
".........KsSSsK.........",
"......KRRRrrrrRRRK......",
".....KRRRRRWWRRRRRK.....",
".....KrRRRRrrRRRRrK.....",
".....KrRRRRrrRRRRrK.....",
".....KrRRRRrrRRRRrK.....",
".....KSrrrrrrrrrrSK.....",
".......KBBBbbBBBK.......",
".......KBBBbbBBBK.......",
".......KBBBKKBBBK.......",
".......KbbbKKbbbK.......",
".......KWWWKKWWWK.......",
"......KWWWWKKWWWWK......",
"......KDDDDKKDDDDK......"
]
},
{
"name": "BYTE",
"accent": "#6bd66b",
"rows": [
"...........WW...........",
".........KKWWKK.........",
".......KBBBBBBBBK.......",
"......KBBBBBBBBBBK......",
".....KBBBBBBBBBBBBK.....",
".....KbbbbbbbbbbbbK.....",
".....KYYSSSSSSSSYYK.....",
".....KYYShSSSShSYYK.....",
".....KYYSKKSSKKSYYK.....",
".....KYYSWKSSWKSYYK.....",
".....KYYSsSSSSsSYYK.....",
".....KYYSSKrrKSSYYK.....",
"......KYSSssssSSYK......",
"........KSSSSSSK........",
".........KsSSsK.........",
"......KGGGggggGGGK......",
".....KGGGGGYYGGGGGK.....",
".....KgGGGYYYYGGGgK.....",
".....KgGGGGYYGGGGgK.....",
".....KgGGGGggGGGGgK.....",
".....KSggggggggggSK.....",
".......KLLLDDLLLK.......",
".......KLLLDDLLLK.......",
".......KLLLKKLLLK.......",
".......KDDDKKDDDK.......",
".......KWWWKKWWWK.......",
"......KWWWWKKWWWWK......",
"......KggggKKggggK......"
]
},
{
"name": "NOVA",
"accent": "#5db4ff",
"rows": [
"...........RR...........",
".........KRRRRK.........",
"........KRRRRRRK........",
"......KRRRRRRRRRRK......",
".....KRRRRRRRRRRRRK.....",
".....KRRrrRRRRrrRRK.....",
".....KRRRRRRRRRRRRK.....",
".....KrrSSSSSSSSrrK.....",
".....KrrSrSSSSrSrrK.....",
".....KrrSKKSSKKSrrK.....",
".....KrrSWKSSWKSrrK.....",
".....KrrSsSSSSsSrrK.....",
".....KrrSSKrrKSSrrK.....",
"......KrSSssssSSrK......",
"........KSSSSSSK........",
".........KsSSsK.........",
"......KBBBbbbbBBBK......",
".....KBBBBBYYBBBBBK.....",
".....KbBBBBbbBBBBbK.....",
".....KbBBBBbbBBBBbK.....",
".....KbBBBBbbBBBBbK.....",
".....KSbbbbbbbbbbSK.....",
".......KLLLDDLLLK.......",
".......KLLLDDLLLK.......",
".......KLLLKKLLLK.......",
".......KDDDKKDDDK.......",
".......KWWWKKWWWK.......",
"......KWWWWKKWWWWK......",
"......KDDDDKKDDDDK......"
]
},
{
"name": "CHIP",
"accent": "#ffd54a",
"rows": [
"........KYYYYYYK........",
"......KYYYYYYYYYYK......",
".....KYYYYYYYYYYYYK.....",
".....KYYYYYhhYYYYYK.....",
".....KYYYYYSSYYYYYK.....",
".....KYYSSSSSSSSYYK.....",
".....KYYShSSSShSYYK.....",
".....KYYSKKSSKKSYYK.....",
"...KKKYYSWKSSWKSYYKKK...",
"..KKYKYYSsSSSSsSYYKYKK..",
".KKYYKYYSSKrrKSSYYKYYKK.",
".KKYY.KYSSssssSSYK.YYKK.",
"..KYK...KSSSSSSK...KYK..",
"...K.....KsSSsK.....K...",
"......KGGGggggGGGK......",
".....KGGGGGWWGGGGGK.....",
".....KgGGGGggGGGGgK.....",
".....KgGGGGggGGGGgK.....",
".....KgGGGGggGGGGgK.....",
".....KSggggggggggSK.....",
".......KBBBbbBBBK.......",
".......KBBBbbBBBK.......",
".......KBBBKKBBBK.......",
".......KbbbKKbbbK.......",
".......KWWWKKWWWK.......",
"......KWWWWKKWWWWK......",
"......KLLLLKKLLLLK......"
]
},
{
"name": "GLITCH",
"accent": "#6bd66b",
"rows": [
"...........GG...........",
"..........KGGK..........",
".........KSGGSK.........",
"........KSSGGSSK........",
".......KSSSGGSSSK.......",
"......KSSSSGGSSSSK......",
".....KSSSSSSSSSSSSK.....",
".....KSSSgSSSSgSSSK.....",
".....KSSSKKSSKKSSSK.....",
".....KSSSWKSSWKSSSK.....",
".....KSSSsSSSSsSSSK.....",
".....KSSSSKrrKSSSSK.....",
"......KSSSssssSSSK......",
"........KSSSSSSK........",
".........KsSSsK.........",
"......KLLLDDDDLLLK......",
".....KLLLLLRRLLLLLK.....",
".....KDLLLLDDLLLLDK.....",
".....KDLLLLDDLLLLDK.....",
".....KDLLLLDDLLLLDK.....",
".....KSDDDDDDDDDDSK.....",
".......KBBBbbBBBK.......",
".......KBBBbbBBBK.......",
".......KBBBKKBBBK.......",
".......KbbbKKbbbK.......",
".......KWWWKKWWWK.......",
"......KWWWWKKWWWWK......",
"......KDDDDKKDDDDK......"
]
},
{
"name": "ACE",
"accent": "#ff5d5d",
"rows": [
"........KBBBBBBK........",
"......KBBBBRRBBBBK......",
".....KBBBBBBBBBBBBK.....",
".....KBbBBBBBBBBbBK.....",
".....KbbbbbbbbbbbbK.....",
".....KhhSSSSSSSShhK.....",
".....KhhShSSSShShhK.....",
".....KhhSKKSSKKShhK.....",
".....KhhSWKSSWKShhK.....",
".....KhhSsSSSSsShhK.....",
".....KhhSSKrrKSShhK.....",
"......KhSSssssSShK......",
"........KSSSSSSK........",
".........KsSSsK.........",
"......KRRRrrrrRRRK......",
".....KRRRRRYYRRRRRK.....",
".....KrRRRRrrRRRRrK.....",
".....KrRRRRrrRRRRrK.....",
".....KrRRRRrrRRRRrK.....",
".....KSrrrrrrrrrrSK.....",
".......KLLLDDLLLK.......",
".......KLLLDDLLLK.......",
".......KLLLKKLLLK.......",
".......KDDDKKDDDK.......",
".......KWWWKKWWWK.......",
"......KWWWWKKWWWWK......",
"......KDDDDKKDDDDK......"
]
},
{
"name": "ZED",
"accent": "#c2c7d0",
"rows": [
".........KKKKKK.........",
".......KDDDDDDDDK.......",
"......KDDDDDDDDDDK......",
".....KRRRRRRRRRRRRK.....",
".....KDDDDDDDDDDDDK.....",
".....KDDSSSSSSSSDDK.....",
".....KDDSKKSSKKSDDK.....",
".....KDDSWKSSWKSDDK.....",
"......KDDDDDDDDDDK......",
"......KDDDDDDDDDDK......",
"........KDDDDDDK........",
".........KDDDDK.........",
"......KDDDKKKKDDDK......",
".....KDDDDDRRDDDDDK.....",
".....KKDDDDKKDDDDKK.....",
".....KKDDDDKKDDDDKK.....",
".....KKDDDDKKDDDDKK.....",
".....KSKKKKKKKKKKSK.....",
".......KDDDKKDDDK.......",
".......KDDDKKDDDK.......",
".......KDDDKKDDDK.......",
".......KKKKKKKKKK.......",
".......KWWWKKWWWK.......",
"......KWWWWKKWWWWK......",
"......KDDDDKKDDDDK......"
]
},
{
"name": "BOLT",
"accent": "#5db4ff",
"rows": [
"...........YY...........",
"...........LL...........",
".......KLLLLLLLLK.......",
"......KLLLLLLLLLLK......",
".....KLLLLLLLLLLLLK.....",
".....KLDDDDDDDDDDLK.....",
".....KLDBWBBBBWBDLK.....",
".....KLDBBBBBBBBDLK.....",
"......KLLLLLLLLLLK......",
"......KLKLKLKLKLLK......",
"........KLLLLLLK........",
".........KLLLLK.........",
"......KLLLDDDDLLLK......",
".....KLLLLLRRLLLLLK.....",
".....KDLLLLDDLLLLDK.....",
".....KDLLLLDDLLLLDK.....",
".....KDLLLLDDLLLLDK.....",
".....KSDDDDDDDDDDSK.....",
".......KLLLDDLLLK.......",
".......KLLLDDLLLK.......",
".......KLLLKKLLLK.......",
".......KDDDKKDDDK.......",
".......KWWWKKWWWK.......",
"......KWWWWKKWWWWK......",
"......KDDDDKKDDDDK......"
]
}
],
"font": {
"A": [
"01110",
"10001",
"10001",
"11111",
"10001",
"10001",
"10001"
],
"B": [
"11110",
"10001",
"10001",
"11110",
"10001",
"10001",
"11110"
],
"C": [
"01110",
"10001",
"10000",
"10000",
"10000",
"10001",
"01110"
],
"D": [
"11110",
"10001",
"10001",
"10001",
"10001",
"10001",
"11110"
],
"E": [
"11111",
"10000",
"10000",
"11100",
"10000",
"10000",
"11111"
],
"F": [
"11111",
"10000",
"10000",
"11100",
"10000",
"10000",
"10000"
],
"G": [
"01110",
"10001",
"10000",
"10111",
"10001",
"10001",
"01110"
],
"H": [
"10001",
"10001",
"10001",
"11111",
"10001",
"10001",
"10001"
],
"I": [
"11111",
"00100",
"00100",
"00100",
"00100",
"00100",
"11111"
],
"J": [
"00111",
"00010",
"00010",
"00010",
"10010",
"10010",
"01100"
],
"K": [
"10001",
"10010",
"10100",
"11000",
"10100",
"10010",
"10001"
],
"L": [
"10000",
"10000",
"10000",
"10000",
"10000",
"10000",
"11111"
],
"M": [
"10001",
"11011",
"10101",
"10101",
"10001",
"10001",
"10001"
],
"N": [
"10001",
"11001",
"10101",
"10101",
"10011",
"10001",
"10001"
],
"O": [
"01110",
"10001",
"10001",
"10001",
"10001",
"10001",
"01110"
],
"P": [
"11110",
"10001",
"10001",
"11110",
"10000",
"10000",
"10000"
],
"Q": [
"01110",
"10001",
"10001",
"10001",
"10101",
"10010",
"01101"
],
"R": [
"11110",
"10001",
"10001",
"11110",
"10100",
"10010",
"10001"
],
"S": [
"01111",
"10000",
"10000",
"01110",
"00001",
"00001",
"11110"
],
"T": [
"11111",
"00100",
"00100",
"00100",
"00100",
"00100",
"00100"
],
"U": [
"10001",
"10001",
"10001",
"10001",
"10001",
"10001",
"01110"
],
"V": [
"10001",
"10001",
"10001",
"10001",
"10001",
"01010",
"00100"
],
"W": [
"10001",
"10001",
"10001",
"10101",
"10101",
"11011",
"10001"
],
"X": [
"10001",
"10001",
"01010",
"00100",
"01010",
"10001",
"10001"
],
"Y": [
"10001",
"10001",
"01010",
"00100",
"00100",
"00100",
"00100"
],
"Z": [
"11111",
"00001",
"00010",
"00100",
"01000",
"10000",
"11111"
],
"0": [
"01110",
"10001",
"10011",
"10101",
"11001",
"10001",
"01110"
],
"1": [
"00100",
"01100",
"00100",
"00100",
"00100",
"00100",
"01110"
],
"2": [
"01110",
"10001",
"00001",
"00110",
"01000",
"10000",
"11111"
],
"3": [
"11110",
"00001",
"00001",
"01110",
"00001",
"00001",
"11110"
],
"4": [
"00010",
"00110",
"01010",
"10010",
"11111",
"00010",
"00010"
],
"5": [
"11111",
"10000",
"11110",
"00001",
"00001",
"10001",
"01110"
],
"6": [
"01110",
"10000",
"10000",
"11110",
"10001",
"10001",
"01110"
],
"7": [
"11111",
"00001",
"00010",
"00100",
"01000",
"01000",
"01000"
],
"8": [
"01110",
"10001",
"10001",
"01110",
"10001",
"10001",
"01110"
],
"9": [
"01110",
"10001",
"10001",
"01111",
"00001",
"00001",
"01110"
],
" ": [
"00000",
"00000",
"00000",
"00000",
"00000",
"00000",
"00000"
],
"-": [
"00000",
"00000",
"00000",
"11111",
"00000",
"00000",
"00000"
],
".": [
"00000",
"00000",
"00000",
"00000",
"00000",
"01100",
"01100"
],
"!": [
"00100",
"00100",
"00100",
"00100",
"00100",
"00000",
"00100"
],
":": [
"00000",
"01100",
"01100",
"00000",
"01100",
"01100",
"00000"
],
"/": [
"00001",
"00010",
"00100",
"00100",
"01000",
"10000",
"10000"
],
"+": [
"00000",
"00100",
"00100",
"11111",
"00100",
"00100",
"00000"
],
"<": [
"00010",
"00100",
"01000",
"10000",
"01000",
"00100",
"00010"
],
">": [
"01000",
"00100",
"00010",
"00001",
"00010",
"00100",
"01000"
],
"*": [
"00000",
"00000",
"00100",
"01110",
"00100",
"00000",
"00000"
]
},
"ball": [
".....KKKKKK.....",
"...KKWWWWWWKK...",
"..KWWWWWWWWWLLK.",
".KWWWWWKKWWWWLLK",
".KWWWKKKKKKWWLLK",
"KWWWWKKKKKKWWWLK",
"KWWWWWKKKKWWWWLK",
"KWWWWWWKKWWWWWLK",
"KWWWWWWWWWWWWWLK",
"KWWKKWWWWWWKKWLK",
"KWWKKKWWWWKKKWLK",
".KWWKKWWWWKKWLLK",
".KWWWWWWWWWWLLK.",
"..KWWWWWWWWLLK..",
"...KKWWWWLLKK...",
".....KKKKKK....."
],
"wingUp": [
".......KK..",
".....KKWWK.",
"...KKWWWWK.",
".KKWWWWWLK.",
"KWWWWWWLK..",
"KWWWWWLK...",
".KWWWLK....",
"..KKKK....."
],
"wingDown": [
"..KKKK.....",
".KWWWLK....",
"KWWWWWLK...",
"KWWWWWWLK..",
".KKWWWWWLK.",
"...KKWWWWK.",
".....KKWWK.",
".......KK.."
],
"graveyard": {
"palette": {
".": null,
"K": "#100c1c",
"N": "#211d3a",
"V": "#34305a",
"v": "#4e4a7e",
"S": "#6d6a92",
"M": "#9a9ab8",
"L": "#d2d4e6",
"G": "#16281c",
"g": "#234a2e",
"m": "#356b3c",
"D": "#2c2016",
"d": "#5e4329",
"W": "#cfe6ff",
"Y": "#ffd86b",
"E": "#79d36a"
},
"monster": [
"......KKKK......",
"....KKEEEEKK....",
"...KEEEEEEEEK...",
"..KEEEEEEEEEEK..",
"..KEWWKEEEKWEK..",
"..KEWWKEEEKWEK..",
"..KEEEEggEEEEK..",
"..KELKLKLKLLEK..",
"..KEEKKKKKKEEK..",
"...KEEEEEEEEK...",
"....KKEEEEKK....",
".KKK..KEEK..KKK.",
"KEEEK.KEEK.KEEEK",
"KEEEKKDDDDKKEEEK",
".KKKKKDDDDDKKKKK",
".....KDDgDDK....",
".....KDDDDDK....",
".....KKDDDKK....",
"....KDDK.KDDK...",
"....KEEK.KEEK...",
"....KKKK.KKKK..."
],
"crypt": [
"..........KKKKKKKKKKKKKKKKKK..........",
".........KMMMMMMMMMMMMMMMMMMK.........",
"........KMMMMMMMMMMMMMMMMMMMMK........",
".......KMLLLLLLLLLLLLLLLLLLLMK........",
"......KMMMMMMMMMMMMMMMMMMMMMMMK.......",
".....KKKKKKKKKKKKKKKKKKKKKKKKKKK......",
"....KMSMMMMMMMMMMMMMMMMMMMMMMMSMK.....",
"....KMSMLMMMMMMMMMMMMMMMMMMMLMSMK.....",
"....KMSMLMMSSSSSSSSSSSSSSMMMLMSMK.....",
"....KMSMLMMSKKKKKKKKKKKKSMMMLMSMK.....",
"....KMSMLMMSKNNNNNNNNNNKSMMMLMSMK.....",
"....KMSMLMMSKNNKKKKKKNNKSMMMLMSMK.....",
"....KMSMLMMSKNKWWWWWWKNKSMMMLMSMK.....",
"....KMSMLMMSKNKWYYYYWKNKSMMMLMSMK.....",
"....KMSMLMMSKNKWYEEYWKNKSMMMLMSMK.....",
"....KMSMLMMSKNKWYEEYWKNKSMMMLMSMK.....",
"....KMSMLMMSKNKWYYYYWKNKSMMMLMSMK.....",
"....KMSMLMMSKNKWWWWWWKNKSMMMLMSMK.....",
"....KMSMMMMSKNNKKKKKKNNKSMMMMSMK......",
"....KSSSSSSSKNNNNNNNNNNKSSSSSSSK......",
"....KSSSSSSSKKKKKKKKKKKKSSSSSSSK......",
"...KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK.....",
"..mggmgKSSSSSSSSSSSSSSSSSSSSKgmggm....",
".mgggggmKKKKKKKKKKKKKKKKKKKKmggggg...."
],
"headstone": [
"...KKKKKK....",
"..KMMMMMMK...",
".KMMLLLLMMK..",
".KMLMMMMSMK..",
".KMLMSSMMSMK.",
".KMLMSSMMSMK.",
".KMLMMMMMSMK.",
".KMLMMMMMSMK.",
".KMLMMMMMSMK.",
".KMMMMMMMSMK.",
".KMMMMMMMMMK.",
"KKSSSSSSSSSKK",
"KmgKSSSSSKgmK",
".mggKKKKKggm.",
"..mgg gg gm.."
],
"broken": [
".....KKK..",
"....KMSK..",
"...KMMSK..",
".KKMMMSK..",
"KMMLMMSK..",
"KMLMMMSKK.",
"KMMMMMMSK.",
"KMMMSSMSK.",
"KMMMMMMSK.",
"KSSSSSSSK.",
"KmgKKKKgmK",
".mgggggm.."
],
"tomb": [
"..KKKKKKKKKKKKKK..",
".KMMMMMMMMMMMMMMK.",
"KMLLLLLLLLLLLLLMK.",
"KMLMMMMMMMMMMMSMK.",
"KSMMMMMMMMMMMMSSK.",
"KSSMMMMMMMMMMSSSK.",
"KSSSSSSSSSSSSSSSK.",
".KSSSSSSSSSSSSSK..",
"..KKKKKKKKKKKKK...",
"..mggm..mggm..g..."
],
"tree": [
"......K...K......",
"...K..K...K..K...",
"....K.KK.KK.K.K..",
".K...KK.K.KK...K.",
"..K.K.KKdKK.K.K..",
"...KK..KdK..KK...",
".....KK.K.KK.....",
".......KdK.......",
".......KdK.......",
"......KdddK......",
"......KdddK......",
"......KDddK......",
"......KdddK......",
"......KDddK......",
".....KDdddDK.....",
"....KKDdddDKK....",
"...mggKKdKKggm...",
"..mgggmKKKmgggm.."
],
"fence": [
"K..K..K..K..K..K.",
"K..K..K..K..K..K.",
"KSSKSSKSSKSSKSSK.",
"K..K..K..K..K..K.",
"K..K..K..K..K..K.",
"KMKKMKKMKKMKKMKK."
],
"pillar": [
".KKKK.",
"KMMMMK",
"KMLLMK",
"KMMMMK",
"KSMMSK",
"KSSSSK",
"KMMMMK",
"KMMMMK",
"KMMMMK",
"KSSSSK",
"KKKKKK"
],
"lantern": [
"..KK..",
".KYYK.",
"KYWWYK",
"KYWWYK",
"KYYYYK",
".KYYK.",
"..KK..",
"..dd..",
"..dd..",
"..dd..",
".KddK."
],
"skull": [
".KKKK.",
"KLLLLK",
"KLKKLK",
"KLKKLK",
"KLLLLK",
".KLLK.",
".KKKK."
],
"bat": [
"K.KKK.K",
"KKNNNKK",
".KNNNK.",
"..KKK.."
]
},
"blocks": {
"palette": {
".": null,
"K": "#14111c",
"M": "#2b2f3c",
"W": "#eef2ff",
"H": "#9aa2b4",
"S": "#6c7384",
"s": "#464c5e",
"P": "#8c5c32",
"p": "#583721",
"L": "#5cc44c",
"g": "#2f8a3a",
"r": "#9e4c2c",
"R": "#683018",
"m": "#b6bccc",
"Y": "#ffc450",
"A": "#182448"
},
"stone": [
"HHHHHHHMHHHHHHHM",
"SSSSSSSMSSSSSSSM",
"SssssssMSssssssM",
"MMMMMMMMMMMMMMMM",
"HHHMHHHHHHHMHHHH",
"SSSMSSSSSSSMSSSS",
"SssMSssssSsMSsss",
"MMMMMMMMMMMMMMMM",
"HHHHHHHMHHHHHHHM",
"SSSSSSSMSSSSSSSM",
"SssssssMSssssssM",
"MMMMMMMMMMMMMMMM",
"HHHMHHHHHHHMHHHH",
"SSSMSSSSSSSMSSSS",
"SssMSssssSsMSsss",
"MMMMMMMMMMMMMMMM"
],
"stoneTop": [
"LLLLLLLLLLLLLLLL",
"LLLLLLLLLLLLLLLL",
"gLggLgggLggLgggL",
"HHHMHHHHHHHMHHHH",
"SSSMSSSSSSSMSSSS",
"SssMSssssSsMSsss",
"MMMMMMMMMMMMMMMM",
"HHHHHHHMHHHHHHHM",
"SSSSSSSMSSSSSSSM",
"SssssssMSssssssM",
"MMMMMMMMMMMMMMMM",
"HHHMHHHHHHHMHHHH",
"SSSMSSSSSSSMSSSS",
"SssMSssssSsMSsss",
"MMMMMMMMMMMMMMMM",
"HHHHHHHMHHHHHHHM"
],
"wood": [
"PPPpPPPpPPPpPPPp",
"PmPpPPPpPmPpPPPp",
"PPPpPpPpPPPpPpPp",
"PPPpPPPpPPPpPPPp",
"PpPpPPPpPpPpPPPp",
"PPPpPPPpPPPpPPPp",
"PPPpPpPpPPPpPpPp",
"PPPpPPPpPPPpPPPp",
"PPPpPPPpPPPpPPPp",
"PpPpPPPpPpPpPPPp",
"PPPpPPPpPPPpPPPp",
"PPPpPpPpPPPpPpPp",
"PmPpPPPpPmPpPPPp",
"PPPpPPPpPPPpPPPp",
"PPPpPPPpPPPpPPPp",
"pppppppppppppppp"
],
"ground": [
"LLLLLLLLLLLLLLLL",
"LLLLLLLLLLLLLLLL",
"gLggLgggLggLgggL",
"rrrrrrrMrrrrrrrM",
"rRRRRRRMrRRRRRRM",
"RRRRRRRMRRRRRRRM",
"MMMMMMMMMMMMMMMM",
"rrrMrrrrrrrMrrrr",
"rRRMrRRRRRRMrRRR",
"RRRMRRRRRRRMRRRR",
"MMMMMMMMMMMMMMMM",
"rrrrrrrMrrrrrrrM",
"rRRRRRRMrRRRRRRM",
"RRRRRRRMRRRRRRRM",
"MMMMMMMMMMMMMMMM",
"rrrMrrrrrrrMrrrr"
],
"dirt": [
"rrrrrrrMrrrrrrrM",
"rRRRRRRMrRRRRRRM",
"RRRRRRRMRRRRRRRM",
"MMMMMMMMMMMMMMMM",
"rrrMrrrrrrrMrrrr",
"rRRMrRRRRRRMrRRR",
"RRRMRRRRRRRMRRRR",
"MMMMMMMMMMMMMMMM",
"rrrrrrrMrrrrrrrM",
"rRRRRRRMrRRRRRRM",
"RRRRRRRMRRRRRRRM",
"MMMMMMMMMMMMMMMM",
"rrrMrrrrrrrMrrrr",
"rRRMrRRRRRRMrRRR",
"RRRMRRRRRRRMRRRR",
"MMMMMMMMMMMMMMMM"
],
"crate": [
"KKKKKKKKKKKKKKKK",
"KmPPPPPPPPPPPPmK",
"KPpPPPPPPPPPpPPK",
"KPPpPPPPPPPpPPPK",
"KPPPpPPPPPpPPPPK",
"KPPPPpPPPpPPPPPK",
"KPPPPPpPpPPPPPPK",
"KPPPPPPpPPPPPPPK",
"KPPPPPpPpPPPPPPK",
"KPPPPpPPPpPPPPPK",
"KPPPpPPPPPpPPPPK",
"KPPpPPPPPPPpPPPK",
"KPpPPPPPPPPPpPPK",
"KmPPPPPPPPPPPPmK",
"KKKKKKKKKKKKKKKK",
"KppppppppppppppK"
],
"vine": [
"..KgLg..",
"..KgLg..",
".KgLLg..",
"..KgLg..",
"..KgLg..",
".KgLLg..",
"..KgLg..",
"..KgLg..",
"KgLLg...",
"..KgLg..",
"..KgLg..",
"..KgLg..",
".KgLLg..",
"..KgLg..",
"..KgKg..",
"..Kg...."
],
"tree": [
".....KK.....",
"...KKggKK...",
"..KgggggsK..",
".KgggggggsK.",
"KggggggggssK",
"KggggggggssK",
".KgggggggsK.",
".KsgggggssK.",
"..KsgggssK..",
"...KKpK KK..",
".....Kp.....",
".....Kp.....",
"....KppK...."
]
},
"crown": {
"palette": {
"K": "#1c1630",
"W": "#ffffff",
"Y": "#ffd23e",
"y": "#c4851a",
"R": "#ff4d5e",
"r": "#b8243c",
"F": "#e6b878",
"f": "#b07c44",
"S": "#b9b3cf",
"s": "#6b6690",
"U": "#5a78d0",
"u": "#2a2660",
"G": "#5fd06b",
"M": "#ff7ad0",
"C": "#ffe9a0",
"D": "#181436"
},
"crownBig": [
"..K.....K.....K..",
"..K.K...K...K.K..",
".KYKYK.KYK.KYKYK.",
".KYRYKKKYKKKYRYK.",
".KYYYYYYYYYYYYYK.",
".KYYRYYYWYYYRYYK.",
".KYYYYYYYYYYYYYK.",
".KyyyyyyyyyyyyyK.",
".KKKKKKKKKKKKKKK."
],
"crownSmall": [
"K.K.K",
"KYKYK",
"YYYYY",
"YRYRY",
"yyyyy"
],
"pillar": [
".KKKKKK.",
"KYYYYYYK",
"KYWWWWYK",
"KKKKKKKK",
"KRRRRRRK",
"KWWWWWWK",
"KRRRRRRK",
"KWWWWWWK",
"KRRRRRRK",
"KWWWWWWK",
"KRRRRRRK",
"KWWWWWWK",
"KRRRRRRK",
"KKsssssK",
"KSssssSK",
"KSsssssK",
".KKKKKK."
],
"maps": [
{
"bg": "crown_map1.png",
"scale": 4,
"bounds": {
"l": 12,
"r": 228,
"t": 22,
"b": 140
},
"obstacles": [
{
"type": "circle",
"x": 34,
"y": 50,
"r": 6
},
{
"type": "circle",
"x": 210,
"y": 50,
"r": 6
},
{
"type": "circle",
"x": 34,
"y": 130,
"r": 6
},
{
"type": "circle",
"x": 210,
"y": 130,
"r": 6
}
],
"spawn": {
"p1": [
44,
98
],
"p2": [
196,
98
],
"crown": [
120,
81
]
}
},
{
"bg": "crown_map2.png",
"scale": 4,
"bounds": {
"l": 12,
"r": 228,
"t": 22,
"b": 140
},
"obstacles": [
{
"type": "rect",
"x": 113,
"y": 40,
"w": 14,
"h": 80
}
],
"spawn": {
"p1": [
44,
80
],
"p2": [
196,
80
],
"crown": [
120,
38
]
}
}
]
},
"tileblitz": {
"palette": {
"K": "#201438",
"W": "#ffffff",
"N": "#b9b3cf",
"n": "#847ea6",
"R": "#ff5d6c",
"r": "#c23350",
"B": "#4fb8ff",
"b": "#2462c0",
"Y": "#ffd23e",
"C": "#bdeaff",
"P": "#7a45c8",
"p": "#43286f",
"G": "#4fd66b",
"M": "#ff7ad0",
"D": "#261c4a"
},
"tileTemplate": [
"hhhhhhhhhhhhhhh#",
"h**oooooooooooo#",
"h*ooooooooooooo#",
"hoooooooooooooo#",
"hoooooooooooooo#",
"hoooooooooooooo#",
"hoooooooooooooo#",
"hoooooooooooooo#",
"hoooooooooooooo#",
"hoooooooooooooo#",
"hoooooooooooooo#",
"hoooooooooooooo#",
"hoooooooooooooo#",
"hoooooooooooooo#",
"hoooooooooooooo#",
"################"
],
"tileColors": {
"N": {
"h": "#d6d2ea",
"o": "#b9b3cf",
"#": "#6b6690",
"*": "#ffffff"
},
"R": {
"h": "#ff9aa6",
"o": "#ff5d6c",
"#": "#b3324a",
"*": "#ffe2e6"
},
"B": {
"h": "#9bd8ff",
"o": "#4fb8ff",
"#": "#2356a8",
"*": "#e2f3ff"
}
},
"bumper": [
".....KKKKKK.....",
"...KKYYYYYYKK...",
"..KYYYYYYYYYYK..",
".KYYYYYYYYYYYYK.",
".KYYYYYWWYYYYYK.",
"KYYYYWWWWWWYYYYK",
"KYYYWWWWWWWWYYYK",
"KYYYWWCCCCWWYYYK",
"KYYYWWCCCCWWYYYK",
"KYYYWWWWWWWWYYYK",
"KYYYYWWWWWWYYYYK",
".KYYYYYWWYYYYYK.",
".KYYYYYYYYYYYYK.",
"..KYYYYYYYYYYK..",
"...KKYYYYYYKK...",
".....KKKKKK....."
],
"meta": {
"scale": 4,
"cell": 16,
"cols": 14,
"rows": 8,
"ox": 8,
"oy": 14,
"bounds": {
"l": 12,
"r": 228,
"t": 18,
"b": 138
},
"bumpers": [],
"spawn": {
"p1": [
32,
118
],
"p2": [
208,
38
]
},
"bg": "tileblitz_bg.png"
}
},
"hotpotato": {
"palette": {
"K": "#1a1620",
"W": "#f5f5fa",
"S": "#b0b8c6",
"s": "#6c7484",
"M": "#302c3c",
"F": "#606878",
"f": "#485060",
"Y": "#ffd03c",
"y": "#c6961e",
"R": "#eb483c",
"r": "#9c2826",
"O": "#ff8e34",
"o": "#ca621a",
"C": "#fff0b4",
"D": "#14121c",
"U": "#4a76c4"
},
"bomb": [
".......C..",
"......CYC.",
".......YO.",
".......o..",
"......so..",
".....ss...",
"...KKKKK..",
"..KMMMMMK.",
".KMMMMMMMK",
".KMSWMMMMK",
"KMMMMMMMMK",
"KMMMMMMMMK",
"KMMMMMMMMK",
".KMMMMMMK.",
".KMMMMMMK.",
"..KKMMKK..",
"...KKKK..."
],
"bombSmall": [
"....C..",
"...CYC.",
"....YO.",
"....o..",
"..KKKK.",
".KMMMMK",
"KMSWMMK",
"KMMMMMK",
".KMMMK.",
"..KKK.."
],
"boom": [
"....K...K....K..",
".K..KYK.KYK.K...",
"..K.YOYKYOY.K.K.",
"...KYOOYOOYK....",
".KKYOORRROOYKK..",
"..KYORRWRRROYK..",
".KYOORWWWROOYK.K",
"KKYORRWWWRRROYKK",
".KYOORWWWROOYK.K",
"..KYORRWRRROYK..",
".KKYOORRROOYKK..",
"...KYOOYOOYK....",
"..K.YOYKYOY.K.K.",
".K..KYK.KYK.K...",
"....K...K....K.."
],
"maps": [
{
"bg": "hotpotato_map1.png",
"scale": 4,
"bounds": {
"l": 12,
"r": 228,
"t": 22,
"b": 140
},
"spawn": {
"p1": [
50,
80
],
"p2": [
190,
80
]
},
"obstacles": [
{
"type": "circle",
"x": 45,
"y": 55,
"r": 6
},
{
"type": "circle",
"x": 195,
"y": 55,
"r": 6
},
{
"type": "circle",
"x": 45,
"y": 107,
"r": 6
},
{
"type": "circle",
"x": 195,
"y": 107,
"r": 6
}
]
},
{
"bg": "hotpotato_map2.png",
"scale": 4,
"bounds": {
"l": 12,
"r": 228,
"t": 22,
"b": 140
},
"spawn": {
"p1": [
16,
80
],
"p2": [
224,
80
]
},
"obstacles": [
{
"type": "rect",
"x": 4,
"y": 16,
"w": 85,
"h": 4
},
{
"type": "rect",
"x": 4,
"y": 45,
"w": 32,
"h": 4
},
{
"type": "rect",
"x": 56,
"y": 45,
"w": 33,
"h": 4
},
{
"type": "rect",
"x": 4,
"y": 16,
"w": 4,
"h": 33
},
{
"type": "rect",
"x": 85,
"y": 16,
"w": 4,
"h": 6
},
{
"type": "rect",
"x": 85,
"y": 42,
"w": 4,
"h": 7
},
{
"type": "rect",
"x": 151,
"y": 16,
"w": 85,
"h": 4
},
{
"type": "rect",
"x": 151,
"y": 45,
"w": 32,
"h": 4
},
{
"type": "rect",
"x": 203,
"y": 45,
"w": 33,
"h": 4
},
{
"type": "rect",
"x": 151,
"y": 16,
"w": 4,
"h": 6
},
{
"type": "rect",
"x": 151,
"y": 42,
"w": 4,
"h": 7
},
{
"type": "rect",
"x": 232,
"y": 16,
"w": 4,
"h": 33
},
{
"type": "rect",
"x": 4,
"y": 111,
"w": 32,
"h": 4
},
{
"type": "rect",
"x": 56,
"y": 111,
"w": 33,
"h": 4
},
{
"type": "rect",
"x": 4,
"y": 140,
"w": 85,
"h": 4
},
{
"type": "rect",
"x": 4,
"y": 111,
"w": 4,
"h": 33
},
{
"type": "rect",
"x": 85,
"y": 111,
"w": 4,
"h": 6
},
{
"type": "rect",
"x": 85,
"y": 137,
"w": 4,
"h": 7
},
{
"type": "rect",
"x": 151,
"y": 111,
"w": 32,
"h": 4
},
{
"type": "rect",
"x": 203,
"y": 111,
"w": 33,
"h": 4
},
{
"type": "rect",
"x": 151,
"y": 140,
"w": 85,
"h": 4
},
{
"type": "rect",
"x": 151,
"y": 111,
"w": 4,
"h": 6
},
{
"type": "rect",
"x": 151,
"y": 137,
"w": 4,
"h": 7
},
{
"type": "rect",
"x": 232,
"y": 111,
"w": 4,
"h": 33
}
]
},
{
"bg": "hotpotato_map3.png",
"scale": 4,
"bounds": {
"l": 12,
"r": 228,
"t": 22,
"b": 140
},
"spawn": {
"p1": [
62,
28
],
"p2": [
150,
130
]
},
"obstacles": [
{
"type": "rect",
"x": 117,
"y": 16,
"w": 6,
"h": 24
},
{
"type": "rect",
"x": 117,
"y": 60,
"w": 6,
"h": 40
},
{
"type": "rect",
"x": 117,
"y": 120,
"w": 6,
"h": 24
},
{
"type": "rect",
"x": 4,
"y": 77,
"w": 24,
"h": 6
},
{
"type": "rect",
"x": 48,
"y": 77,
"w": 144,
"h": 6
},
{
"type": "rect",
"x": 212,
"y": 77,
"w": 24,
"h": 6
}
]
}
]
}
};
