"""Hand-authored sprite grids for the couch-party characters (front-facing idle)."""

# ---------------------------------------------------------------------------
# PLAYER 1 — "PIXEL"  : brown side-swept hair, red hoodie, blue jeans, sneakers
# 24 wide grid.  Every glyph is a palette index from render.PALETTE
# ---------------------------------------------------------------------------
PIXEL = r"""
.........KKKKKK.........
.......KhhhhhhhhK.......
......KhhhHHHhhhhK......
.....KhhhhHHhhhhhhK.....
.....KhhhSSSSSShhhK.....
.....KhhSSSSSSSShhK.....
.....KhhShSSSShShhK.....
.....KhhSKKSSKKShhK.....
.....KhhSWKSSWKShhK.....
.....KhhSsSSSSsShhK.....
.....KhhSSKrrKSShhK.....
......KhSSssssSShK......
........KSSSSSSK........
.........KsSSsK.........
......KRRRrrrrRRRK......
.....KRRRRRWWRRRRRK.....
.....KrRRRRrrRRRRrK.....
.....KrRRRRrrRRRRrK.....
.....KrRRRRrrRRRRrK.....
.....KrRRRRrrRRRRrK.....
.....KSrrrrrrrrrrSK.....
.......KBBBbbBBBK.......
.......KBBBbbBBBK.......
.......KBBBKKBBBK.......
.......KbbbKKbbbK.......
.......KWWWKKWWWK.......
......KWWWWKKWWWWK......
......KDDDDKKDDDDK......
"""

# ---------------------------------------------------------------------------
# PLAYER 2 — "BYTE" : blue beanie w/ pom, blonde hair, green hoodie + star,
#                     grey joggers, green-soled sneakers
# ---------------------------------------------------------------------------
BYTE = r"""
...........WW...........
.........KKWWKK.........
.......KBBBBBBBBK.......
......KBBBBBBBBBBK......
.....KBBBBBBBBBBBBK.....
.....KbbbbbbbbbbbbK.....
.....KYYSSSSSSSSYYK.....
.....KYYShSSSShSYYK.....
.....KYYSKKSSKKSYYK.....
.....KYYSWKSSWKSYYK.....
.....KYYSsSSSSsSYYK.....
.....KYYSSKrrKSSYYK.....
......KYSSssssSSYK......
........KSSSSSSK........
.........KsSSsK.........
......KGGGggggGGGK......
.....KGGGGGYYGGGGGK.....
.....KgGGGYYYYGGGgK.....
.....KgGGGGYYGGGGgK.....
.....KgGGGGggGGGGgK.....
.....KgGGGGggGGGGgK.....
.....KSggggggggggSK.....
.......KLLLDDLLLK.......
.......KLLLDDLLLK.......
.......KLLLKKLLLK.......
.......KDDDKKDDDK.......
.......KWWWKKWWWK.......
......KWWWWKKWWWWK......
......KggggKKggggK......
"""
