"""Export roster sprites, the 16-color palette, and the pixel font to a JS
data file the browser game loads directly (no server / CORS needed)."""
import json, os
from render import PALETTE
import pixelfont as pf
import characters as C
import graveyard as GY

GAME = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "game")
os.makedirs(GAME, exist_ok=True)

palette = {k: (None if v is None else "#%02x%02x%02x" % v) for k, v in PALETTE.items()}
roster = [{"name": n, "accent": a, "rows": s.split("\n")} for (n, s, a) in C.ROSTER]
font = {k: v for k, v in pf.G.items()}

gy_palette = {k: (None if v is None else "#%02x%02x%02x" % v) for k, v in GY.PAL.items()}
graveyard = {
    "palette": gy_palette,
    "monster": GY.MONSTER, "crypt": GY.CRYPT, "headstone": GY.HEADSTONE,
    "cross": GY.CROSS, "broken": GY.BROKEN, "tomb": GY.TOMB, "tree": GY.DEAD_TREE,
    "fence": GY.FENCE, "pillar": GY.PILLAR, "lantern": GY.LANTERN,
    "skull": GY.SKULL, "bat": GY.BAT,
}

data = {"palette": palette, "roster": roster, "font": font,
        "ball": C.BALL.split("\n"),
        "wingUp": C.WING_UP.split("\n"), "wingDown": C.WING_DOWN.split("\n"),
        "graveyard": graveyard}
out = os.path.join(GAME, "data.js")
with open(out, "w") as f:
    f.write("// AUTO-GENERATED by art/export_json.py — do not edit by hand.\n")
    f.write("window.GAME_DATA = " + json.dumps(data, indent=0) + ";\n")
print("wrote", out, "(roster:", len(roster), "chars)")
